# Generated by Django 4.0.4 on 2022-06-02 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('altura', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='familia.persona')),
                ('tipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.IntegerField()),
            ],
            bases=('familia.persona', models.Model),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('vehiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='familia.vehiculo')),
                ('especie', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
            ],
            bases=('familia.vehiculo', models.Model),
        ),
    ]
